### ISSUE TITLE
Environment is "DEMO" not "Microsoft Graph environment" as mentioned in docs

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/microsoftgraph-postman-collections#1]
After importing the environment, the docs imply that the environment is named **Microsoft Graph environment** when it is really named **DEMO**.

Scenario:
- MacOS
- Postman v7.0.6

**Comment by jthake** [comment]
Thanks @andrewconnell !

**Comment by jthake** [comment]
Fixed this in latest commit https://github.com/microsoftgraph/microsoftgraph-postman-collections/commit/331d381e39e7cdcd52fe05c452d0ef0d7817d3e3
