### ISSUE TITLE
Authentication using Certificates

### ISSUE THREAD

**Issue by gitsreerao** [microsoftgraph/microsoftgraph-postman-collections#10]
Thanks for putting together this postman collection. 
Is there a guide for testing it with certs (instead of the client_secret)?

**Comment by jthake** [comment]
I"m still investigating this one...sorry for delay.

**Comment by jthake** [comment]
OK so further investigation.

Here is a stackoverflow post that explains what the request called are
https://stackoverflow.com/questions/39354835/what-happens-during-a-acquiretokenasync-call-using-the-client-certificate/39371624#39371624

For those following along , here is more details on auth with certificates:

- Client credentials flow using a certificate: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#second-case-access-token-request-with-a-certificate
- Format of the client_assertion (a JWT signed by the authorized certificate): https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials
