### ISSUE TITLE
Scope does not include Application Permission "Contacts.Read" even with granted admin consent

### ISSUE THREAD

**Issue by MagdelynBlue** [microsoftgraph/microsoftgraph-postman-collections#12]
I added Contacts.Read under MS Graph > Application Permission > Contacts.Read and have the administrated to grand the admin consent.
![image](https://user-images.githubusercontent.com/52396976/60414002-6f73a780-9c09-11e9-91e5-a73033cf7f27.png)

But I don't know why when I retrieve the access token, it does not include Contacts.Read in scope, also when I try to decode the access_token with jwt, I don't see "Roles" in the claim.
```
{
    "token_type": "Bearer",
    "scope": "profile openid email https://graph.microsoft.com/User.Read https://graph.microsoft.com/.default",
    "expires_in": 3600,
    "ext_expires_in": 3600,
    "access_token": "{MY_TOKEN_HERE}"
}
```

**Comment by jthake** [comment]
/Sorry i didn't have notifications on in this repo and didn't get this issues ;-( my bad.

DId you resolve this? Where you doing "Get access token" in the application folder, and not the delegated (on behalf of user) folder. As you have set calednar.read as a application permission not delegated.

**Comment by jthake** [comment]
Closing as 20 days old and no response.
