### ISSUE TITLE
Request to add PATCH to add content to an existing OneNote Page

### ISSUE THREAD

**Issue by emtgenius** [microsoftgraph/microsoftgraph-postman-collections#14]
Tested (OneNote) Get Notebooks, Get sections and Get Pages - all worked like a charm - what a treasure you have created, Jeremy... Thanks a million!!
I humbly request to add PATCH to add content to an existing OneNote Page. It will be immensely useful to the community. I don't have that level of expertise... Thanks!

**Comment by jthake** [comment]
Thank you @emtgenius . Sorry I only just saw this. My notifications on this repo were not set up.

I"d actually need to go speak to the OneNote team to find out the best example of this. In Graph Explorer I don't believe we have this example either...

**Comment by jasonjoh** [comment]
Closing this as we're no longer maintaining the collection in GitHub. Collection is now hosted at https://www.postman.com/microsoftgraph/workspace/microsoft-graph/overview.
