### ISSUE TITLE
Missing a beta version

### ISSUE THREAD

**Issue by jsuddsjr** [microsoftgraph/microsoftgraph-postman-collections#15]
A lot more functionality is coming. When can we try it out?

See [https://docs.microsoft.com/en-us/graph/overview?view=graph-rest-beta](https://docs.microsoft.com/en-us/graph/overview?view=graph-rest-beta)

**Comment by jthake** [comment]
To date we hadn't gone as far as doing beta api calls. We were first trying to make sure that the collections format and structure was working for v1.0 the way its laid out and splitting between User and Application. Our usage isn't high enough yet to valdiate that thinking and we haven't got much signal one way or the other yet.
Once our usage is a bit higher we will invest the effort to create the beta api collections. This does become a bit more challenging to keep on top of with beta as lots of change happens here. We are hoping actually to automate the generation of this collection in the same way we generate the samples in Graph Explorer. Graph Explorer actually does not do v1.0 for the same reasons of keeping up with evolving APIs.

I estimate we'll likely have beta in Jan/Feb here.

**Comment by jthake** [comment]
@jsuddsjr  out of interest, what workloads would you like to see from beta in the collection?

**Comment by v4rden** [comment]
Does it mean that there will be separate collection for v1.0 and beta (and versions to come)?
Alternatively introduce {{apiVersion}} environment value. Then user can setup what to use (ofc if he choses v1.0 for method from beta api it will fail, but no need to keep separate collections)

**Comment by jasonjoh** [comment]
Closing this as we're no longer maintaining the collection in GitHub. Collection is now hosted at https://www.postman.com/microsoftgraph/workspace/microsoft-graph/overview.
