### ISSUE TITLE
Add to Postman Network

### ISSUE THREAD

**Issue by kinlane** [microsoftgraph/microsoftgraph-postman-collections#16]
I would love to see this collection in the Postman network - https://explore.postman.com/network/search?q=graph

**Comment by jthake** [comment]
Hi Kin, I actually spoke to Joyce from Postman yesterday. I'm meeting with her after Microsoft Ignite conference next week to talk about this and a whole heap of other things we'd like to do with Postman. Thanks for validating me driving for this!

**Comment by kinlane** [comment]
LOL -- Joyce mentioned she was talking to someone at Microsoft!  

good to hear -- I am going to be playing with and work up for a story on my api evangelist blog.

Keep up the good work!

**Comment by jasonjoh** [comment]
Well @jthake-msft did it but never resolved this issue :D. We're retiring this repo in favor of https://www.postman.com/microsoftgraph/workspace/microsoft-graph/overview
