### ISSUE TITLE
Sharepoint - Lists

### ISSUE THREAD

**Issue by einue** [microsoftgraph/microsoftgraph-postman-collections#17]
Addding Get/Post-Requests  for sharepoint lists/document libraries would be great.

**Comment by jthake** [comment]
I'll take a look at what those calls look like. The challenge here is going to be that to do that you need a site id etc. which means making those environment variables. 

Get all sites as part of /sites is actually really close to being in beta, so I could list all site collections, get the first one, get the root site and then grab the default document library from that and one of the default custom lists too.

**Comment by jasonjoh** [comment]
Closing this as we're no longer maintaining the collection in GitHub. Collection is now hosted at https://www.postman.com/microsoftgraph/workspace/microsoft-graph/overview.
