### ISSUE TITLE
Empty values when retrieving Items in a list

### ISSUE THREAD

**Issue by kamalsaravanan70** [microsoftgraph/microsoftgraph-postman-collections#18]
I hereby use the following link to get the items present in a specific list 

https://graph.microsoft.com/v1.0/sites/root/lists/{{ListId}}/items

This works well until I started retrieving the items in a list. The output remains empty for any of the lists being called

**Comment by jthake** [comment]
Sorry this repo is for the postman collections, this seems like an issue with using the graph apis. Can you please ask your questions on STackOverflow with tag [microsoft-graph] thanks.
