### ISSUE TITLE
Readme.md has incorrect links to collection and environment json (Step 4)

### ISSUE THREAD

**Issue by praveenbengeri** [microsoftgraph/microsoftgraph-postman-collections#21]
Links mentioned in Step 4 for importing into Postman are incorrect. That is, following are incorrect.

https://raw.githubusercontent.com/microsoftgraph/microsoftgraph-postman-collections/master/Microsoft%20Graph%20.postman_collection.json

https://raw.githubusercontent.com/microsoftgraph/microsoftgraph-postman-collections/master/Microsoft%20Graph%20.postman_environment.json

**Comment by jthake** [comment]
Thank you for pointing this out. I had made a change, but it hadn't been reflected in master. Apologies.

I've fixed this now in this commit https://github.com/microsoftgraph/microsoftgraph-postman-collections/commit/ac2909c64a1f86e033e68c6d9658fd0d39377beb#diff-04c6e90faac2675aa89e2176d2eec7d8
