### ISSUE TITLE
Using Microsoft Graph API to get access to AAD B2C Console .NetCore Console App 

### ISSUE THREAD

**Issue by samanaz** [microsoftgraph/microsoftgraph-postman-collections#22]
Hi guys,

Thanks in advance for your help.

I am developing an application and I am using Azure AD B2C for my customer identity management.
I need to understand how I can use Microsoft Graph API as an Application permissions (without username and password) to get access to B2C user object attributes. I need this for my back-end development.

On postman it works with normal Azure Ad User objects (including B2C user objects) but I cannot see the B2C users attributes. How can I see B2C users attributes and manipulate them? 

I really appreciate your help.

Sincerely yours,
Saman

**Comment by jthake** [comment]
Sorry the issues list for this repo is purely for issues with the postman collection itself.
If you have broader Microsoft Graph questions. Please ask on www.stackoverflow.com and use tags [microsoft-graph] and any relevant tags. For you you'd want to find the B2C tag that the community is using.
