### ISSUE TITLE
Postman Collection issues

### ISSUE THREAD

**Issue by Ranjeet4android** [microsoftgraph/microsoftgraph-postman-collections#25]
I am just import the postman collection and follow the all steps. 
After getting access token when I am using Getuser api then I am getting error.
While I am checking AccessToken is here.
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token is empty.",
        "innerError": {
            "request-id": "8accdd19-b519-434f-baa7-35dacd4c2a47",
            "date": "2020-04-17T09:09:06"
        }
    }
}

Please suggest me where I am wrong.

**Comment by jthake** [comment]
BTW are you doing it for Delegated consent ? as there are two folders...one for delegated and one for application . You will need a different access token for each . There are two different requests you run to get those tokens (Get User Access Token/Get App-only Access Token).. It doesn't hurt to just run both.

When you ran the Get User Access Token did it populate this environment variable in top right?

![image](https://user-images.githubusercontent.com/6786616/79589299-0cfd7200-808a-11ea-8c01-b10ecb947f3c.png)

**Comment by Ravikadri-zz** [comment]
Upgrade the Postman to the latest version. I upgraded to  7.23.0 and it resolved the issue.

I also got the same issue. This is nothing related to Graph collections. Instead, it is related to Postman javascript not working in the postman.
