### ISSUE TITLE
Identity Governance such as Entitlement management and Access reviews

### ISSUE THREAD

**Issue by jonasbjo** [microsoftgraph/microsoftgraph-postman-collections#26]
Should be great to have this included in the collection. I am trying to make this connector so I can manage users in access packages in bulk via Power Automate or Azure Automation. The graph API is still in Beta and I have a hard time getting it to work.

**Comment by jthake** [comment]
I'm following up internally to find the PM who owns this as its shuffled around. i'll round trip back on this next week.

**Comment by jasonjoh** [comment]
Closing this as we're no longer maintaining the collection in GitHub. Collection is now hosted at https://www.postman.com/microsoftgraph/workspace/microsoft-graph/overview.
