### ISSUE TITLE
Postman variables: Initial vs Current

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/microsoftgraph-postman-collections#3]
When I edited the environment, the variables dialog had columns for Initial and Current values. The http calls did not work until the Current values where set.

Is Initial/Current the default view for new users? Should the instructions specify the location to enter the variables? Should the script look at the Initial values (if possible)?

**Comment by jthake** [comment]
The setup instructions do tell you to set the variables. I didn't state between **Current** and **Initial**. Basically it needs to be **Current**. I'll update readme. Thanks Paul!

**Comment by pschaeflein** [comment]
There is a PR for the README with a little cleanup I did...
