### ISSUE TITLE
Bug on payload for Invite User

### ISSUE THREAD

**Issue by gettosin4me** [microsoftgraph/microsoftgraph-postman-collections#35]
[Enter feedback here]

There is a bug on the json payload to invite user, 

Incorrect

```json

    "invitedUserEmailAddress": "<Email Address of Invited User>, 

```

Correct

```json

    "invitedUserEmailAddress": "<Email Address of Invited User>", 

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman?context=graph%2Fapi%2Fbeta&view=graph-rest-beta)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake** [comment]
@gettosin4me thanks for raising this!

**Comment by jthake** [comment]
This is now fixed in the new workspace here https://www.postman.com/microsoftgraph/workspace/microsoft-graph/request/455214-c6b27595-6fd9-4214-ba57-1ca43a0467c9

Sorry this one slipped through :-(
