### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by cybersxp** [microsoftgraph/microsoftgraph-postman-collections#39]
there is a error (Error while importing: format not recognized )when i import the link (https://raw.githubusercontent.com/microsoftgraph/microsoftgraph-postman-collections/master/Microsoft%20Graph.postman_collection.json)

**Comment by jthake** [comment]
I cannot replicate this. @cybersxp  what are the steps you are taking.


Select **File | Import**
Click **Link**
paste `https://raw.githubusercontent.com/microsoftgraph/microsoftgraph-postman-collections/master/Microsoft%20Graph.postman_collection.json`
Click **Continue**
