### ISSUE TITLE
Question: Does the user name and password work with MFA accounts?

### ISSUE THREAD

**Issue by pmatthews05** [microsoftgraph/microsoftgraph-postman-collections#4]
Just watched the video, our environment is locked down with OKTA, would this still work? Also will it work in general with Microsoft MFA enabled?

Thanks.

**Comment by jthake** [comment]
No. this only works when straight user name and password. As per the readme, its not recommended with production environments where things like MFA would be configured. You can obtain a developer environment by signing up for the Office 365 developer program. https://developer.microsoft.com/en-us/office/dev-program

**Comment by jthake** [comment]
Actually sorry, you can achieve this by using the native OAuth2 flow. It's a little more configuration
https://learning.getpostman.com/docs/postman/sending_api_requests/authorization/#oauth-20

You have to use the endpoints from your application in portal.azure.com to do this. Once you have the access token you can add it to your environment variables. This uses a UI to sign the user in.

The other way is to go into Graph Explorer, sign in, use developer console and type `tokenPlease()`

**Comment by pmatthews05** [comment]
Thanks @jthake-msft. I wasn't going to be using this on the production environment, it was for our test environment which mimic's our production environment setup. Unfortunately I have no control of turning off MFA / OKTA in the test environment either. I'll check out the OAuth2 flow. Again thank you.

**Comment by jthake** [comment]
Re-opening as I'm going to add a stream lined flow for the OAuth2 Postman functionality.

**Comment by jthake** [comment]
@pmatthews05 I have written steps now on how to do this. Little bit more work to get going. Please give me any feedback here,

https://github.com/microsoftgraph/microsoftgraph-postman-collections/blob/master/README.md#setting-up-on-behalf-of-delegated-access

**Comment by pmatthews05** [comment]
Hi @jthake-msft ,
 Sorry it's taken me a couple of days to get round to this. I have tested your README.md and it is all correct apart from the callback URL should be "https://app.getpostman.com/oauth2/callback" not "https://www.getpostman.com/oauth2/callback" if you have followed [Day 9 correctly](https://developer.microsoft.com/en-us/graph/blogs/30daysmsgraph-day-9-azure-ad-applications-on-v2-endpoint/).

**Comment by jthake** [comment]
Thanks for the tip. i'll change that.
