### ISSUE TITLE
Bad Request: Invalid filter clause

### ISSUE THREAD

**Issue by datasleek** [microsoftgraph/microsoftgraph-postman-collections#41]
I am using POSTMAN to call Microsoft Graph APIs. I am trying to subscribe to presence for multiple users. It is mentioned in [document](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta) in order to subscribe to changes to multiple user presences use this url  `/communications/presences?$filter=id in ({id},{id}...)`

Request Url ;`https://graph.microsoft.com/beta/subscriptions`
Request Type: `POST`

request body(raw):
```
{ 
  "changeType": "updated", 
  "notificationUrl": "https://d3a8ebc3581d.ngrok.io/presence-notify/", 
  "resource": "/communications/presences?$filter=id in (abcd-efgh-4856-a935-c9a2f685xyz,abcd-efgh-47f8-9d79-eacb0fd6xyz)",
  "expirationDateTime": "2020-09-22T07:37:13Z", 
  "clientState": "secretClientState" 
}
```

I am calling this API on behalf of user i.e i am using UserAccessToken. This is Response:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2020-09-21T16:24:50",
            "request-id": "2cf476f0-2270-417f-a987-5c5bbc92a351",
            "client-request-id": "2cf476f0-2270-417f-a987-5c5bbc92a351"
        }
    }
}
```

**P.S: I have changed first few and last few characters of both the user ids. So it's not an issue.**

**Comment by baywet** [comment]
Hey @datasleek 
Thanks for reaching out. Here is a few things I'd like you to try to understand the issue better:
- Can you try with single quotes around the guids?
- Can you try with a single id?(with this pattern)
- Can you try with a single id? (with /communications/presences/id)
- What happens if you try with IncludeResourceData set to true and the encryptionCertificate?

**Comment by jthake** [comment]
@datasleek I've raised an internal service issue on this with the engineering group. I'll get back soon on this.

**Comment by elvinyang-msft** [comment]
@datasleek please note the ids in the list need to be wrapped by single quote.

**Incorrect:**
"resource": "/communications/presences?$filter=id in (abcd-efgh-4856-a935-c9a2f685xyz,abcd-efgh-47f8-9d79-eacb0fd6xyz)",
**Correct:**
"resource": "/communications/presences?$filter=id in ('abcd-efgh-4856-a935-c9a2f685xyz','abcd-efgh-47f8-9d79-eacb0fd6xyz')",
