### ISSUE TITLE
Post Get User Access Token bounces

### ISSUE THREAD

**Issue by Josiah-Keppel** [microsoftgraph/microsoftgraph-postman-collections#47]
Tried to follow the instructions on the YouTube video (https://www.youtube.com/watch?v=4tg-OBdv_8o) by typing adding in the credentials of Microsoft Graph environment. 

However, when trying the post method to get an user access token, I get back a 404 error instead of the token body which is automatically copied to the environment variables. 

Would like some help on troubleshooting this issue.
![image](https://user-images.githubusercontent.com/48664732/97660511-c367f800-1aac-11eb-8e6d-f164122632d9.png)

**Comment by jthake** [comment]
if you are getting a 404. That means the url in the reuqest is incorrect. the only variable there is `TenantID`. Can you make sure in your environment you ahve tht aset. In Postman you can hover over the curly braces reference to `TenantID` and it'll show if it has a value or not.

**Comment by Josiah-Keppel** [comment]
Thanks for the clarification. However, I have a new issue as well. I'm currently getting error message as well after I sent the post request. 
Understand that I need to trigger the Multi-factor authentication window. 
Can I do it using the POST request?

![Postman test Graph Token error](https://user-images.githubusercontent.com/48664732/99646991-2507fa80-2a8c-11eb-927d-705aef9853f4.PNG)

**Comment by Ravikadri-zz** [comment]
Looks like a similar issue addressed [6311](https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/6306). Can you check and see if that fixes the issue.

Let me know.

Thanks!
Ravi

**Comment by jthake** [comment]
closing as no response since Nov. Hopefully you got this sorted out.
