### ISSUE TITLE
Got a 403 when using calendarview

### ISSUE THREAD

**Issue by andushow** [microsoftgraph/microsoftgraph-postman-collections#48]
Hello,

- I have managed so far to auth using this endpoint

https://login.microsoftonline.com/{{TenantID}}/oauth2/v2.0/token
But i cannot `Get others event for next week`
https://graph.microsoft.com/v1.0/users/{{**my_email@address**}}/calendarview?startdatetime={{Today}}&enddatetime={{NextWeek}}&$select=Subject,Start,End&$orderBy=start/dateTime&$top=1000
The response i get is 403 +
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again.",
        "innerError": {
            "date": "2020-11-05T19:09:21",
            "request-id": "25418588-04a5-48dc-ab46-40cf843f4782",
            "client-request-id": "25418588-04a5-48dc-ab46-40cf843f4782"
        }
    }
}

- The app i use to auth has the following rights:

https://graph.microsoft.com/Calendars.Read 
https://graph.microsoft.com/Calendars.ReadWrite
https://graph.microsoft.com/User.Read 
https://graph.microsoft.com/User.Read.All 
https://graph.microsoft.com/User.ReadBasic.All 
https://graph.microsoft.com/.default

- The `service account` user (used to get the auth token) has (full) permission on my calendar and yet is not able to get my events.

What am i missing ?
Thanks,

**Comment by jthake** [comment]
Sorry this is not a location to troubleshoot graph issues, this issue list is purely for postman collection issues.

Can you post your question here please? https://docs.microsoft.com/en-us/answers/topics/ms-graph-calendar.html
