### ISSUE TITLE
Incomplete Postman collection

### ISSUE THREAD

**Issue by gdhnz** [microsoftgraph/microsoftgraph-postman-collections#52]
Looking at the collection in Postman, it doesn't contain the full API spec referenced in the documentation at https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0.

**Comment by jthake** [comment]
You are correct it does not. This is a personal project I have been running to try and prove that there is enough demand for this to warrant more effort from our engineering team to do more of the APIs. 
We are about to publish a new iteration of this which you can see here https://www.youtube.com/watch?v=3RTHY3jScmA&t=41s

**Comment by gdhnz** [comment]
I've created a fork but see it's the same spec as linked in the MS documentation.

Will the new iteration included the complete API spec?  Is there a timeframe on when it will be released.
