### ISSUE TITLE
Question: Does this work with enterprise AD accounts?

### ISSUE THREAD

**Issue by jackal47** [microsoftgraph/microsoftgraph-postman-collections#7]
I went through tons of documentation and tutorials, but couldn't make the user token work. App-Only Access Tokens work as expected, but with User Access Tokens I get the following errors:

1. if I set the field "userName" without "@domain":
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS50034: The user account Microsoft.AzureAD.Telemetry.Diagnostics.PII does not exist in the xxxxxxxxxxx directory. To sign into this application, the account must be added to the directory.\r\nTrace ID: xxxxxx\r\nCorrelation ID: xxxxxxx\r\nTimestamp: 2019-04-09 13:59:11Z",
    "error_codes": [
        50034
    ],
    "timestamp": "2019-04-09 13:59:11Z",
    "trace_id": "xxxxxxx",
    "correlation_id": "xxxxxxx"
}
```

2. with "@domain" in username I get error:
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS50126: Invalid username or password.\r\nTrace ID: xxxxxxxxxxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxxxxxxxxxx\r\nTimestamp: 2019-04-09 13:54:38Z",
    "error_codes": [
        50126
    ],
    "timestamp": "2019-04-09 13:54:38Z",
    "trace_id": "xxxxxxx",
    "correlation_id": "xxxxxxx"
}
```

My app has the following permissions:
Mail.Read, Mail.ReadBasic, Mail.Send, User.Read

None of the above requires Admin Consent, so I think the API permissions are fine.

What I want to do is to automate some actions based on emails my account receives.

**Comment by jthake** [comment]
You will require to consent for the user through an interactive page if you do not do the admin consent approach that I show in the video embeddded on the readme page.
Just for validation, if you go to Graph Explorer and sign in as this user and grant those permissions does it work?

**Comment by jackal47** [comment]
Thanks Jeremy,

As I understand, application permissions are required for my app to allow signing in without redirecting. The problem is that app permission to read email is too much for me as it allows reading emails of all users in organization.
My goal is to use a background app which reads emails of a specific user who's credentials are used to authenticate through my app. It's a backend service which needs to take some actions based on received emails. It has it's own AD account for this purpose.
Is there a way to log in with this user using only REST API and delegated permissions?
Webhooks would also work for me if my service wasn't in a private cloud, so at the moment I think my only solution is to authenticate with REST somehow.

**Comment by jackal47** [comment]
Thanks Jeremy,

As I understand, application permissions are required for my app to allow signing in without redirecting. The problem is that app permission to read email is too much for me as it allows reading emails of all users in organization.
My goal is to use a background app which reads emails of a specific user who's credentials are used to authenticate through my app. It's a backend service which needs to take some actions based on received emails. It has it's own AD account for this purpose.
Is there a way to log in with this user using only REST API and delegated permissions?
Webhooks would also work for me if my app wasn't in a private cloud, so at the moment I think my only solution is to authenticate with REST somehow.

**Comment by jthake** [comment]
Sorry i never replied here. But for delegated (on-behalf-of) permissions you can also use Postman authorization tab in requests which I describe here
https://github.com/microsoftgraph/microsoftgraph-postman-collections#setting-up-on-behalf-of-delegated-access
