### ISSUE TITLE
Cannot get Tests to run

### ISSUE THREAD

**Issue by spg-iwilson** [microsoftgraph/microsoftgraph-postman-collections#8]
I've been able to set up the collection and generate the UserAccessToken. However, the script in Tests aren't working for me. When I click the Test Results tab, I see the message "There are no tests for this request". 

I followed the walkthrough lesson for running tests in Postman. They use the following demo test:

pm.test("Status code is 200", function () { pm.response.to.have.status(200); });

If I replace the test for the "Get User Access Token" with this example, the test runs. Have I missed a configuration step?

**Comment by jthake** [comment]
Sorry for the late reply. notifications weren't being sent to my mail for this repo. Totally missed this.

The tests aren't actually required, they are there to help.  The exception to this is the Get User Access Token and Get App-Only Token. As when these requests complete it takes the token and stores it in the environment variable. If you click on the eye in the top right, you should see the UserAccessToken variable populated. Can you confirm this?

**Comment by jthake** [comment]
Closing due to no response.
