### ISSUE TITLE
Number of requests inside batch exceed the limit.

### ISSUE THREAD

**Issue by rcosta86** [microsoftgraph/microsoftgraph-postman-collections#9]
Hi all,

First of all, thanks for your contributions and sorry I don´t have a lot of knowledge about Graph.
I need some help. I´m working with Graph to try to retrieve all messages for all users for my environment, to see the number of attachments and sizes (Yes, I know this is crazy). I build a JSON for retrieve this data but I found if the users that I can retrieve is greater than 6, Graph not working and send me the following error: "Number of requests inside batch exceeds the limit.".

Method used: POST https://graph.microsoft.com/v1.0/$batch

Example JSON created: {"requests": [{"id": "1","method": "GET","url": "/users/pip@domain.OnMicrosoft.com/messages?$select=id,receivedDateTime,sentDateTime,hasAttachments,subject,sender,from&$expand=attachments($select=contentType,id,name,size)"}]}

In my JSON, I have all the users including.

Do you have any idea to solve this issue? I thinking if I make a paging response maybe can be solved, but I don´t know how I doing it that.

Many thanks.

**Comment by jthake** [comment]
Sorry for the slow reply, i wasn't getting alerts for my own repo for some reason!

What you are trying to do is outside the limits of batch.  You'd have to do this sort of thing in your code and iterate through your users mailboxes one by one. 

You're going to want to respect the throttling on Microsoft Graph service through the 429 response codes too. And be extremely careful on payload and use the select to get back just what you need.  https://docs.microsoft.com/en-us/graph/throttling

Have you considered using Microsoft Graph data connect for this scenario? https://docs.microsoft.com/en-us/graph/data-connect-overview
